primary:
  persistence:
    size: 30Gi

metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    namespace: observability
    interval: 30s
    scrapeTimeout: 10s
    labels:
      release: kube-prom-stack

networkPolicy:
  enabled: true
  allowExternal: false
