name: Create TLS secret

on:
  workflow_dispatch:
    inputs:
      namespace:
        description: "namespace"
        required: true
        type: string

jobs:
  deploy:
    environment: PROD
    name: Create tls secret in namespace=${{github.event.inputs.namespace}}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up sops
        run: |
          mkdir -p ~/.config/sops/age
          echo "${{ secrets.SOPS_AGE_KEY}}" | base64 -d > ~/.config/sops/age/keys.txt
          curl -sLo sops https://github.com/mozilla/sops/releases/download/v3.8.1/sops-v3.8.1.linux.amd64
          chmod +x sops
          sudo mv sops /usr/local/bin/sops

      - name: Set up kubectl
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG_CONTENT }}" | base64 -d > ~/.kube/config
          chmod 600 ~/.kube/config
          kubectl config use-context jw-prod

      - name: Create tls
        run: |
          make ENV=PROD TLS_NAMESPACE=${{ github.event.inputs.namespace }} tls/create
