name: Infra deployments

on:
  workflow_dispatch:
    inputs:
      task:
        description: "Choose what to do"
        required: true
        default: "config"
        type: choice
        options:
          - config/deploy
          - keycloak/install
          - postgres/install

jobs:
  deploy:
    environment: PROD
    name: Run install - ${{ github.event.inputs.task }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up kubectl
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG_CONTENT }}" | base64 -d > ~/.kube/config
          chmod 600 ~/.kube/config
          kubectl config use-context jw-prod

      - name: Set up Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Deploy config
        if: ${{ github.event.inputs.task == 'config/deploy' }}
        run: |
          mkdir -p ~/.config/sops/age
          echo "${{ secrets.SOPS_AGE_KEY}}" | base64 -d > ~/.config/sops/age/keys.txt
          curl -sLo sops https://github.com/mozilla/sops/releases/download/v3.8.1/sops-v3.8.1.linux.amd64
          chmod +x sops
          sudo mv sops /usr/local/bin/sops
          make ENV=PROD config/deploy

      - name: Install Keycloak
        if: ${{ github.event.inputs.task == 'keycloak/install' }}
        run: make ENV=PROD keycloak/install

      - name: Install Postgres
        if: ${{ github.event.inputs.task == 'postgres/install' }}
        run: make ENV=PROD postgres/install

      - name: Cleanup
        run: rm ~/.kube/config

